/**
 * Hub i18n — Language packs cho layui.i18n
 * Hỗ trợ: vi (Tiếng Việt), en (English), zh-CN (中文)
 *
 * Sử dụng:
 *   HubLang.init()           — load ngôn ngữ đã lưu, set layui.i18n
 *   HubLang.setLang('en')    — đổi ngôn ngữ, lưu localStorage, apply DOM
 *   HubLang.applyDOM()       — scan data-i18n attributes và dịch
 *   HubLang.t(key)           — đọc trực tiếp từ appMessages (sync)
 */

var HubLang = (function () {
  var STORAGE_KEY = 'hub_lang';
  var DEFAULT_LANG = 'vi';

  var LANGS = {
    vi: { label: 'Tiếng Việt', short: 'VN', flag: '/images/vn.gif' },
    en: { label: 'English', short: 'EN', flag: '/images/uk.gif' },
    'zh-CN': { label: '中文', short: 'CN', flag: '/images/china.gif' }
  };

  // ── App-specific messages ──
  var appMessages = {
    vi: {
      // ── Page titles ──
      adminPageTitle: 'Agent Hub — Quản lý',
      loginPageTitle: 'Agent Hub — Đăng nhập',

      // ── Header ──
      toggleMenu: 'Thu gọn menu',
      reload: 'Tải lại trang',
      fullscreen: 'Toàn màn hình',
      language: 'Ngôn ngữ',
      changeLoginPw: 'Đổi MK đăng nhập',
      changeFundPw: 'Đổi MK giao dịch',
      logout: 'Đăng xuất',
      options: 'Tuỳ chọn',
      noOptions: 'Chưa có tuỳ chọn nào.',

      // ── Sidebar ──
      memberMgmt: 'Quản lí hội viên',
      members: 'Hội viên',
      generalFeatures: 'Tính năng chung',
      revenueCalc: 'Tính doanh thu',
      promotionAnalysis: 'Phân tích Ưu đãi',
      customerQuality: 'Chất lượng khách hàng',
      qcGroupQuality: 'Chất lượng nhóm QC',
      qcTotalGroups: 'Tổng nhóm',
      qcTotalMembers: 'Tổng thành viên',
      qcActiveMembers: 'Hoạt động',
      qcTotalDeposit: 'Tổng nạp',
      qcGroup: 'Nhóm',
      qcMembers: 'Thành viên',
      qcActive: 'Hoạt động',
      dbLotteryBet: 'Cược XS',
      dbThirdBet: 'Cược NCC',
      agentReport: 'Báo cáo chi tiết từng đại lý',
      comingSoon: 'Tính năng đang phát triển...',
      referralCode: 'Mã giới thiệu',
      reports: 'Báo cáo',
      lotteryReport: 'BC xổ số',
      transStatement: 'Sao kê giao dịch',
      providerReport: 'BC nhà cung cấp',
      commission: 'Rút hoa hồng',
      deposit: 'Nạp tiền',
      withdraw: 'Rút tiền',
      betOrders: 'Đơn cược',
      lotteryBet: 'Đơn cược xổ số',
      thirdPartyBet: 'Cược bên thứ 3',
      customer: 'Khách hàng',
      rebateRate: 'Tỉ lệ hoàn trả',
      management: 'Quản lý',
      manageAgents: 'Quản lý Agents',
      manageUsers: 'Quản lý Users',

      // ── Tabs context ──
      closeTab: 'Đóng',
      closeOther: 'Đóng tab khác',
      closeRight: 'Đóng tab bên phải',
      closeAll: 'Đóng tất cả',

      // ── Login ──
      loginTitle: 'Đăng nhập',
      username: 'Tên đăng nhập',
      password: 'Mật khẩu',
      loginBtn: 'Đăng nhập',
      loginSubtitle: 'Hệ thống quản lý Đại lý',
      fillAllFields: 'Vui lòng nhập đầy đủ thông tin',
      captchaPlaceholder: 'Mã xác nhận',
      captchaClickRefresh: 'Click hình để đổi mã',
      captchaWrong: 'Mã xác nhận không đúng',
      loginSuccess: 'Đăng nhập thành công!',
      loginFailed: 'Đăng nhập thất bại',
      connectionError: 'Lỗi kết nối',
      mustChangePwMsg:
        'Bạn đang dùng mật khẩu mặc định. Vui lòng đổi mật khẩu ngay để bảo mật tài khoản.',
      securityWarning: 'Cảnh báo bảo mật',
      changePwNow: 'Đổi ngay',
      later: 'Để sau',

      // ── Common UI ──
      search: 'Tìm kiếm',
      reset: 'Đặt lại',
      confirm: 'Xác nhận',
      submit: 'Gửi đi',
      cancel: 'Huỷ',
      select: 'Chọn',
      all: 'Tất cả',
      noData: 'Không có dữ liệu',
      actions: 'Thao tác',
      edit: 'Sửa',
      delete: 'Xoá',
      active: 'Hoạt động',
      locked: 'Khoá',
      stopped: 'Ngừng',
      failed: 'Thất bại',
      updated: 'Đã cập nhật',
      deleted: 'Đã xoá',
      error: 'Lỗi',
      serverError: 'Lỗi kết nối server',

      // ── Common data fields ──
      accountName: 'Tên tài khoản',
      enterAccountName: 'Nhập tên tài khoản',
      serialNo: 'Mã giao dịch',
      enterSerialNo: 'Nhập mã giao dịch',
      account: 'Tài khoản',
      agent: 'Đại lý',
      amount: 'Số tiền',
      trueAmount: 'Thực nhận',
      createTime: 'Thời gian tạo',
      updateTime: 'Cập nhật',
      status: 'Trạng thái',
      time: 'Thời gian',
      id: 'ID',
      uid: 'UID',
      agentId: 'ID Đại lý',
      agentTree: 'Cây Đại lý',
      groupId: 'Nhóm',
      remark: 'Ghi chú',

      // ── Date filters ──
      today: 'Hôm nay',
      yesterday: 'Hôm qua',
      thisWeek: 'Tuần này',
      thisMonth: 'Tháng này',
      lastMonth: 'Tháng trước',
      dateStartEnd: 'Chọn khoảng thời gian',
      dateStartEndTime: 'Chọn khoảng thời gian',
      summaryData: 'Dữ liệu tổng hợp:',

      // ── Status values ──
      statusPending: 'Chờ xử lí',
      statusDone: 'Hoàn tất',
      statusProcessing: 'Đang xử lí',
      statusFailed: 'Thất bại',
      statusNotEval: 'Chưa đánh giá',
      statusNormal: 'Bình thường',
      statusFrozen: 'Đóng băng',
      statusWait: 'Chờ',

      // ── Financial columns (shared) ──
      operator: 'Thao tác viên',
      successTime: 'Thời gian hoàn tất',
      firmFee: 'Phí công ty',
      userFee: 'Phí người dùng',
      rebate: 'Hoàn trả',
      accountHolder: 'Chủ tài khoản',
      accountHolderShort: 'Tên chủ TK',
      bankId: 'Ngân hàng',
      branch: 'Chi nhánh',
      accountNo: 'Số tài khoản',
      transferTime: 'Thời gian CK',
      userRemark: 'Ghi chú KH',
      proStatus: 'Trạng thái xử lí',
      prizeAmount: 'Tiền thưởng',
      activityId: 'ID khuyến mãi',
      extraInfo: 'Thông tin thêm',
      categoryId: 'Danh mục',
      merchantId: 'Nhà cung cấp',
      payType: 'Hình thức TT',
      tradeId: 'Mã thanh toán',
      isTester: 'Thử nghiệm',
      reviewTime: 'Thời gian duyệt',
      transferRecord: 'Bản ghi CK',
      currency: 'Tiền tệ',
      balance: 'Số dư',
      betAmount: 'Tiền cược',
      turnover: 'Doanh thu',
      prize: 'Trúng thưởng',
      winLose: 'Thắng / Thua',
      result: 'Kết quả',
      rebateAmount: 'Hoàn trả',
      betTimes: 'Lượt cược',
      validAmount: 'Cược hợp lệ',

      // ── user.html (member management) ──
      memberMgmtSub: 'Quản lí hội viên thuộc cấp',
      addMemberBtn: 'Thêm hội viên',
      addAgentBtn: 'Đại lý mới thêm',
      setRebateBtn: 'Cài đặt hoàn trả',
      firstDepositTime: 'Thời gian nạp đầu',
      sortByField: 'Sắp xếp theo trường',
      sortDirection: 'Sắp xếp theo hướng',
      sortDesc: 'Từ lớn đến bé',
      sortAsc: 'Từ bé đến lớn',
      memberType: 'Loại hình hội viên',
      agentAccount: 'Đại lý',
      member: 'Hội viên',
      depositCount: 'Lần nạp',
      withdrawCount: 'Lần rút',
      totalDeposit: 'Tổng tiền nạp',
      totalWithdraw: 'Tổng tiền rút',
      lastLoginTime: 'Lần đăng nhập cuối',
      registerTime: 'Thời gian đăng ký',
      truename: 'Họ tên',
      phone: 'Điện thoại',
      email: 'Email',
      inviteCode: 'Mã mời',
      device: 'Thiết bị',
      loginIp: 'IP đăng nhập',
      level: 'Cấp độ',
      agentType: 'Loại Đại lý',
      phoneVerified: 'XM điện thoại',
      emailVerified: 'XM email',
      userAgent: 'User Agent',
      lastUpdate: 'Cập nhật cuối',
      noteExtra: 'Ghi chú thêm',
      addNewAgent: 'Thêm Đại lý mới',
      addNewMember: 'Thêm hội viên mới',
      confirmPw: 'Xác nhận MK',
      passwordNoMatch: 'Mật khẩu không khớp',
      agentAdded: 'Đã thêm Đại lý',
      memberAdded: 'Đã thêm hội viên',
      rebateTitle: 'Tỉ lệ hoàn trả',
      rebateUpdated: 'Đã cập nhật hoàn trả',
      rebateSetup: 'Cài đặt hoàn trả — ',
      chars416: '4-16 ký tự',
      chars620: '6-20 ký tự',
      retypePw: 'Nhập lại mật khẩu',

      // ── inviteList.html ──
      addInviteBtn: 'Thêm mã giới thiệu',
      copyLink: 'Copy đường link',
      viewConfig: 'Xem cài đặt',
      qrCode: 'Mã QR',
      editBtn: 'Chỉnh sửa',
      addedTime: 'Thời gian thêm vào',
      memberLoginTime: 'Thời gian hội viên đăng nhập',
      enterInviteCode: 'Nhập đầy đủ mã giới thiệu',
      inviteType: 'Loại hình giới thiệu',
      totalRegistered: 'Tổng số đã đăng ký',
      registeredUsers: 'Số lượng người dùng đã đăng ký',
      rechargeCount: 'Số người nạp tiền',
      firstRechargeDay: 'Nạp đầu trong ngày',
      registerRechargeDay: 'Nạp đầu trong ngày đăng kí',
      rebateArr: 'Hoàn trả',
      copied: 'Đã copy: ',
      configType: 'Loại hình',
      notConfigured: 'Chưa cài đặt',
      editInviteCode: 'Chỉnh sửa mã: ',
      inviteDescription: 'Mô tả mã giới thiệu',
      inviteAdded: 'Đã thêm mã giới thiệu',
      configTitle: 'Cài đặt hoàn trả — ',
      qrTitle: 'Mã QR — ',

      // ── reportLottery.html ──
      reportLotteryTitle: 'Báo cáo xổ số',
      lotteryType: 'Tên loại xổ',
      selectOrSearch: 'Chọn hoặc nhập để tìm kiếm',
      bettersCount: 'Số khách đặt cược',
      betCount: 'Số lần cược',
      validBetAmount: 'Tiền cược hợp lệ (trừ cược hoà)',
      winLoseNoRebate: 'Kết quả thắng thua (không gồm hoàn trả)',
      prizeCol: 'Tiền trúng',
      lotteryName: 'Loại xổ số',
      lotteryId: 'ID xổ số',

      // ── reportFunds.html ──
      transStatementTitle: 'Sao kê giao dịch',
      depositAmountTotal: 'Số tiền nạp',
      withdrawAmountTotal: 'Số tiền rút',
      chargeFee: 'Phí dịch vụ',
      agentCommission: 'Hoa hồng Đại lý',
      promotion: 'Ưu đãi',
      thirdRebate: 'Hoàn trả bên thứ 3',
      thirdActivityAmount: 'Tiền thưởng từ bên thứ 3',
      depositCountCol: 'Số lần nạp',
      withdrawCountCol: 'Số lần rút',
      dateCol: 'Ngày',

      // ── reportThirdGame.html ──
      reportThirdTitle: 'Báo cáo nhà cung cấp game',
      provider: 'Nhà cung cấp',
      betTimesCol: 'Lượt cược',
      bettersCountCol: 'Số người cược',
      providerId: 'ID NCC',

      // ── depositAndWithdrawal.html ──
      depositWithdrawTitle: 'Quản lí nạp / rút tiền',
      typeCol: 'Loại',
      typeDeposit: 'Nạp',
      typeWithdraw: 'Rút',

      // ── withdrawalsRecord.html ──
      withdrawHistoryTitle: 'Lịch sử rút tiền',
      statusFormat: 'Trạng thái',

      // ── bet.html (lottery bets) ──
      betListTitle: 'Danh sách đơn cược',
      userName: 'Tên người dùng',
      enterFullUsername: 'Vui lòng nhập đầy đủ Tên người dùng',
      enterFullSerialNo: 'Nhập đầy đủ mã giao dịch',
      game: 'Trò chơi',
      gameType: 'Loại trò chơi',
      playStyle: 'Cách chơi',
      betStatusUnpaid: 'Chưa thanh toán',
      betStatusWon: 'Trúng',
      betStatusLost: 'Không trúng',
      betStatusDraw: 'Hoà',
      betStatusCancelUser: 'Khách huỷ đơn',
      betStatusCancelSystem: 'Hệ thống huỷ đơn',
      betStatusAbnormal: 'Đơn cược bất thường',
      betStatusUnpaidManual: 'Chưa thanh toán (khôi phục thủ công)',
      betTime: 'Thời gian cược',
      issue: 'Kỳ',
      betContent: 'Thông tin cược',
      betMoney: 'Tiền cược',
      betRebate: 'Tiền hoàn trả',
      betResult: 'Thắng thua',
      totalBetMoney: 'Tiền cược',
      totalRebateAmount: 'Tiền hoàn trả',
      totalWinLose: 'Thắng thua',

      // ── betOrder.html (3rd party bets) ──
      thirdPartyBetTitle: 'Đơn cược bên thứ 3',
      betTimeLabel: 'Thời gian cược',
      platformAccount: 'Tài khoản platform',
      enterPlatformAccount: 'Nhập tài khoản',
      gameCategory: 'Loại game',
      gameName: 'Tên game',
      tkPlatform: 'TK Platform',
      categoryTypeId: 'ID loại',

      // ── editPassword.html ──
      editPwTitle: 'Đổi mật khẩu đăng nhập',
      oldPw: 'Mật khẩu cũ',
      enterOldPw: 'Nhập mật khẩu cũ',
      newPassword: 'Mật khẩu mới',
      confirmNewPw: 'Xác nhận mật khẩu mới',
      enterConfirmNewPw: 'Nhập xác nhận mật khẩu mới',
      pwMismatch: 'Mật khẩu mới và xác nhận không khớp',
      pwChangeSuccess: 'Đổi mật khẩu thành công',
      pwChangeFailed: 'Đổi mật khẩu thất bại',

      // ── editFundPassword.html ──
      editFundPwTitle: 'Đổi mật khẩu giao dịch',
      fundPwOldHint:
        'Bạn vẫn chưa cài đặt mật khẩu giao dịch, mặc định để trống',
      fundPwChangeSuccess: 'Đổi mật khẩu giao dịch thành công',
      fundPwChangeFailed: 'Đổi mật khẩu thất bại',

      // ── getRebateOddsPanel.html ──
      rebateOddsTitle: 'Tỉ lệ hoàn trả',

      // ── admin.html (header dropdown) ──
      accountInfo: 'Thông tin',
      settings: 'Cài đặt',

      // ── manageAgents.html ──
      manageAgentsTitle: 'Quản lý tài khoản Agent EE88',
      solverOn: 'OCR: BẬT',
      solverOff: 'OCR: TẮT',
      baseUrlLabel: 'Base URL',
      addAgentMgmt: 'Thêm Agent',
      checkAll: 'Kiểm tra tất cả',
      check: 'Kiểm tra',
      login: 'Login',
      agentLabel: 'Tên agent',
      baseUrl: 'URL',
      cookie: 'Cookie',
      ee88Account: 'Tài khoản EE88',
      ee88NotConfigured: 'Chưa cấu hình',
      users: 'Users',
      lastLoginCol: 'Login lần cuối',
      lastCheck: 'Kiểm tra',
      noAgents: 'Không có agent nào',
      confirmDeleteAgent: 'Xác nhận xoá agent "',
      deleteAgentPrompt: 'Chọn cách xử lý agent này:',
      disableAgent: 'Vô hiệu hoá',
      deleteAgentFull: 'Xoá hoàn toàn',
      disableAgentHint:
        'Vô hiệu hoá: giữ lại data, kích hoạt lại bất cứ lúc nào',
      confirmHardDelete:
        'Xoá hoàn toàn sẽ xoá agent VÀ toàn bộ dữ liệu đã đồng bộ. Không thể khôi phục!',
      disabled: 'Đã vô hiệu',
      enable: 'Kích hoạt',
      deleteData: 'Xoá data',
      agentEnabled: 'Đã kích hoạt lại agent',
      agentOk: 'Agent hoạt động bình thường',
      agentProblem: 'Agent có vấn đề',
      addNewAgentMgmt: 'Thêm Agent mới',
      editAgentTitle: 'Sửa agent: ',
      autoLoginSection: 'Auto-login EE88 (tuỳ chọn)',
      ee88Username: 'Tên đăng nhập EE88',
      ee88Password: 'Mật khẩu EE88',
      keepEmpty: 'Để trống = giữ nguyên',
      cookieHint: 'PHPSESSID=xxx (để trống nếu dùng auto-login)',
      agentExample: 'VD: Agent 1',
      mgmtAgentAdded: 'Đã thêm agent',
      loginConfirmMsg: 'Login tự động agent "',
      loginProcessHint: 'Quá trình có thể mất 30-60 giây',
      agentLoginSuccess: 'Login thành công',
      agentLoginFailed: 'Login thất bại',
      agentsWorking: ' agent hoạt động',

      // ── manageUsers.html ──
      manageUsersTitle: 'Quản lý tài khoản Hub',
      roleAdmin: 'Admin',
      roleUser: 'User',
      addUserBtn: 'Thêm User',
      permissions: 'Phân quyền',
      displayName: 'Tên hiển thị',
      role: 'Vai trò',
      assignedAgents: 'Agents được phân quyền',
      allAdmin: 'Tất cả (admin)',
      noPermission: 'Chưa phân quyền',
      createdAt: 'Ngày tạo',
      noUsers: 'Không có user nào',
      confirmDeleteUser: 'Xác nhận xoá user "',
      addNewUser: 'Thêm User mới',
      editUserTitle: 'Sửa user: ',
      newPwLabel: 'MK mới',
      keepEmptyPw: 'Để trống nếu không đổi',
      minChars6: 'Ít nhất 6 ký tự',
      userAdded: 'Đã thêm user',
      adminAllAccess: 'Admin có quyền truy cập tất cả agents',
      selectAgentAccess: 'Chọn các agent mà user ',
      selectAgentAccessSuffix: ' được phép truy cập:',
      noAgentYet: 'Chưa có agent nào',
      savePermissions: 'Lưu phân quyền',
      permTitle: 'Phân quyền — ',
      permUpdated: 'Đã cập nhật phân quyền',

      // ── Column Permissions ──
      columnPerm: 'Quyền cột',
      columnPermTitle: 'Quyền cột',
      columnPermDesc: 'Cấu hình cột hiển thị cho user',
      columnPermSaved: 'Đã lưu quyền cột',
      adminAllColumns: 'Admin luôn thấy tất cả cột',
      deselectAll: 'Bỏ chọn',
      page_members: 'Hội viên',
      page_reportLottery: 'BC Xổ số',
      page_reportFunds: 'Sao kê GD',
      page_reportThirdGame: 'BC NCC',
      page_betOrder: 'Đơn cược NCC',
      page_bet: 'Đơn cược XS',
      page_withdrawals: 'Rút tiền',
      page_deposits: 'Nạp tiền',
      page_inviteList: 'Mã mời',
      page_dashboard: 'Tổng quan',
      page_agentReport: 'BC Đại lý',
      page_customerStatus: 'Phân loại KH',
      page_customerRetention: 'Giữ chân KH',
      page_winLossStats: 'Thắng/Thua',
      page_providerAnalysis: 'PT NCC',
      page_lotteryAnalysis: 'PT Xổ số',
      page_depositWithdrawAnalysis: 'PT Nạp/Rút',
      page_promotionAnalysis: 'PT KM',
      page_financialSummary: 'Tổng hợp TC',
      page_detailedGameStats: 'TK Game',
      page_qcGroupQuality: 'CL Nhóm',
      page_revenueCalc: 'Tính doanh thu',

      // ── Export ──
      exportExcel: 'Xuất Excel',

      // ── Dashboard ──
      dashboard: 'Tổng quan',
      dbActiveAgents: 'Agent hoạt động',
      dbExpiredAgents: 'Agent hết hạn',
      dbTotalAgents: 'Tổng agents',
      dbAgentStatus: 'Trạng thái Agent',
      dbLoginStats: 'Thống kê Login (7 ngày)',
      dbLoginSuccess: 'Thành công',
      dbLoginFail: 'Thất bại',
      dbRecentActivity: 'Hoạt động gần đây',
      dbDateRange: 'Khoảng thời gian',
      dbPickDateRange: 'Chọn khoảng thời gian',
      dbLast7Days: '7 ngày',
      dbLast30Days: '30 ngày',
      dbTotalMembers: 'Tổng hội viên',
      dbNewMembers: 'Hội viên mới',
      dbActiveMembers: 'Đang hoạt động',
      dbDepositTotal: 'Tổng nạp',
      dbWithdrawTotal: 'Tổng rút',
      dbNetWinLoss: 'Thắng / Thua ròng',
      dbDepositWithdrawTrend: 'Xu hướng Nạp / Rút',
      dbWinLossBreakdown: 'Phân bố Thắng / Thua',
      dbLotteryWL: 'Xổ số',
      dbThirdPartyWL: 'Bên thứ 3',
      dbPerAgent: 'Chi tiết theo Đại lý',
      dbFirstDeposit: 'Nạp lần đầu',
      dbOrders: 'lệnh',
      dbBetAmount: 'Tổng cược',
      dbPrize: 'Tổng thưởng',
      dbLoading: 'Đang tải...',
      dbError: 'Lỗi tải dữ liệu',
      dbRetry: 'Thử lại',
      dbNet: 'Ròng',
      dbSale: 'Nhân viên sale',
      dbAgentLine: 'Dây Đại lý',
      dbTodayNewCustomers: 'Khách mới hôm nay',
      dbTodayLotteryBet: 'Cược xs hôm nay',
      dbTodayThirdBet: 'Cược NCC hôm nay',
      dbMonthlyLotteryBet: 'Tổng cược xs tháng',
      dbMonthlyThirdBet: 'Tổng cược NCC tháng',
      dbTodayDeposit: 'Nạp hôm nay',
      dbMonthlyDeposit: 'Tổng nạp tháng',
      dbLotteryWLTotal: 'Tổng T/T xổ số',
      dbThirdWLTotal: 'Tổng T/T NCC',

      // ── Activity Log ──
      activityLog: 'Nhật ký',
      activityLogTitle: 'Nhật ký hoạt động',
      actionCol: 'Hành động',
      targetCol: 'Đối tượng',
      ipCol: 'IP',
      detailCol: 'Chi tiết',
      filterAction: 'Lọc hành động',
      filterUsername: 'Lọc người dùng',

      // ── Login All + History ──
      loginAllBtn: 'Login tất cả',
      loginAllConfirm: 'Login tự động tất cả agent hết hạn?',
      loginAllDone: 'Login xong',
      loginHistory: 'Lịch sử',
      loginHistoryTitle: 'Lịch sử login',
      attemptsCol: 'Lần thử',
      durationCol: 'Thời gian (ms)',
      sourceCol: 'Nguồn',
      triggeredByCol: 'Kích hoạt bởi',
      errorCol: 'Lỗi',
      successCol: 'Kết quả',

      // ── realtimeMonitor.html ──
      rtMonitor: 'Giám sát Realtime',
      rtPollingStatus: 'Trạng thái',
      rtNewCustomers: 'Khách mới',
      rtLostCustomers: 'Khách mất',
      rtWsConnections: 'Kết nối WS',
      rtRunning: 'Đang chạy',
      rtStopped: 'Đã dừng',
      rtInterval: 'Interval',
      rtStart: 'Bắt đầu',
      rtStop: 'Dừng',
      rtMarkAllRead: 'Đọc tất cả',
      rtClearAll: 'Xoá tất cả',
      rtAll: 'Tất cả',
      rtNewOnly: 'Khách mới',
      rtLostOnly: 'Khách mất',
      rtUnread: 'Chưa đọc',
      rtNoEvents: 'Chưa có sự kiện nào. Bắt đầu polling để theo dõi.',
      rtNewCustomerDetected: 'Phát hiện khách mới',
      rtLostCustomerDetected: 'Phát hiện khách mất',
      rtParent: 'Đại lý',
      rtLastPoll: 'Poll cuối',
      rtMembers: 'Hội viên',
      rtMarkedRead: 'Đã đánh dấu đọc tất cả',
      rtConfirmClear: 'Xoá tất cả sự kiện realtime?',
      rtRedisOk: 'Redis kết nối',
      rtRedisOff: 'Redis không kết nối',

      // ── syncStatus.html (Phase 6: Cache + Sync) ──
      syncStatus: 'Đồng Bộ',
      syncStatusTitle: 'Trạng thái Đồng Bộ',
      syncNow: 'Đồng bộ ngay',
      clearCache: 'Xoá DB tài khoản đã chọn',
      cacheOverview: 'Tổng quan Cache',
      totalCached: 'Tổng bản ghi',
      totalRows: 'Tổng dòng dữ liệu',
      lockedDays: 'Ngày đã khoá',
      lastSyncTime: 'Đồng bộ lần cuối',
      syncLogs: 'Lịch sử đồng bộ',
      syncSuccess: 'Thành công',
      syncError: 'Lỗi',
      syncPending: 'Chờ',
      syncRunning: 'Đang chạy',
      endpoint: 'Endpoint',
      cachedDate: 'Ngày cache',
      rowCount: 'Số dòng',
      noSyncData: 'Chưa có dữ liệu đồng bộ',
      confirmSync: 'Bắt đầu đồng bộ dữ liệu?',
      noSelection: 'Chưa chọn tài khoản nào',
      confirmClearCache: 'Xác nhận xoá DB các tài khoản đã chọn?',
      syncStarted: 'Đã bắt đầu đồng bộ',
      cacheCleared: 'Đã xoá DB tài khoản đã chọn',
      filterEndpoint: 'Lọc endpoint',
      filterStatus: 'Lọc trạng thái',
      filterAgent: 'Lọc đại lý',
      selectAll: 'Chọn tất cả',
      syncing: 'Đang đồng bộ',
      cacheHit: 'Cache HIT',
      cacheMiss: 'Cache MISS',
      syncProgress: 'Tiến độ',
      dateCount: 'Số ngày',
      noSync: 'Chưa đồng bộ',
      totalAgents: 'Tổng Đại lý',
      fullySynced: 'Đã đồng bộ đủ',
      notSynced: 'Chưa đồng bộ',
      completed: 'Hoàn tất',
      pending: 'Chờ',
      elapsed: 'Thời gian',
      ready: 'Sẵn sàng',
      confirmClearLocks: 'Xoá tất cả khoá ngày?',

      // ── Login (remember) ──
      saveAccount: 'Lưu tài khoản',

      // ── syncStatus.html additional ──
      syncDataTitle: 'Đồng bộ dữ liệu',
      syncBtn: 'Đồng bộ',
      clearLocksBtn: 'Xoá khoá',
      syncAllBtn: 'Đồng bộ tất cả',
      clearSelectedBtn: 'Xoá khoá đã chọn',
      agentDataType: 'Đại lý / Loại dữ liệu',
      dataRows: 'Dòng dữ liệu',
      lockedDaysCol: 'Ngày khoá',
      syncingIndicator: 'Đang đồng bộ...',
      confirmSyncAll: 'Đồng bộ tất cả agents?',
      confirmSyncAgent: 'Đồng bộ',
      confirmClearAgentLocks: 'Xoá tất cả khoá ngày của',
      confirmClearSelectedLocks: 'Xoá khoá ngày của',
      selectedAgents: 'Đại lý đã chọn',

      // ── Endpoint display names (syncStatus) ──
      epMembers: 'Danh sách hội viên',
      epInvites: 'Mã mời',
      epBetOrders: 'Đơn cược bên thứ 3',
      epDeposits: 'Nạp / Rút tiền',
      epWithdrawals: 'Lịch sử rút tiền',
      epLotteryBets: 'Đơn cược xổ số',
      epLotteryBetsSummary: 'Tổng hợp đơn cược XS',
      epReportLottery: 'Báo cáo xổ số',
      epReportFunds: 'Sao kê giao dịch',
      epReportThird: 'Báo cáo NCC game',

      // ── revenueCalc.html ──
      revTotalRevenue: 'Tổng doanh thu',
      revLotteryProfit: 'Lợi nhuận XS',
      revThirdProfit: 'Lợi nhuận NCC',
      revPerAgent: 'Chi tiết theo đại lý',
      revVsPrev: 'so kỳ trước',
      revNewPeriod: 'Kỳ mới (chưa có dữ liệu trước)',

      // ── promotionAnalysis.html ──
      pmTotalPromotion: 'Tổng ưu đãi',
      pmTotalRebate: 'Hoàn trả NCC',
      pmTotalActivity: 'Hoạt động NCC',
      pmPromoRate: 'Tỷ lệ ưu đãi/nạp',
      pmThirdActivity: 'Hoạt động NCC',
      pmRate: 'Tỷ lệ (%)',

      // ── depositWithdrawAnalysis.html ──
      depositWithdrawAnalysis: 'Phân tích Nạp/Rút',
      dwTotalDeposit: 'Tổng nạp',
      dwTotalWithdrawal: 'Tổng rút',
      dwNet: 'Chênh lệch (Nạp - Rút)',
      dwPromotion: 'Ưu đãi',
      dwRebate: 'Hoàn trả',
      dwDailyTrend: 'Xu hướng Nạp/Rút theo ngày',
      dwNetAmount: 'Chênh lệch',

      // ── financialSummary.html ──
      financialSummary: 'Tổng hợp Tài chính',
      fsTotalRevenue: 'Doanh thu',
      fsCost: 'Chi phí',
      fsProfit: 'Lợi nhuận',
      fsMargin: 'Margin',
      fsLotteryWL: 'T/T Xổ số',
      fsThirdWL: 'T/T NCC',
      fsPerAgent: 'Chi tiết theo đại lý',

      // ── customerQuality.html ──
      cqTotalMembers: 'Tổng hội viên',
      cqActiveMembers: 'Đang hoạt động',
      cqInactiveMembers: 'Không hoạt động',
      cqDepositRate: 'Tỷ lệ nạp',
      cqDepositTier: 'Phân loại mức nạp',
      cqWinLossSeg: 'Phân loại thắng/thua',
      cqQualityMetrics: 'Chỉ số chất lượng',
      cqMultiDeposit: 'Nạp nhiều lần',
      cqMultiDepositDesc: 'Khách nạp từ 2 lần trở lên',
      cqHighValue: 'Giá trị cao (≥10M)',
      cqHighValueDesc: 'Tổng nạp từ 10 triệu trở lên',
      cqMultiDepositRate: 'Tỷ lệ nạp lại',
      cqMultiDepositRateDesc: 'Trong số khách đã nạp',
      cqTierZero: 'Chưa nạp (0)',
      cqTierUnder1M: 'Dưới 1M',
      cqTier1to5M: '1-5M',
      cqTier5to10M: '5-10M',
      cqTier10to50M: '10-50M',
      cqTierOver50M: 'Trên 50M',
      cqWinners: 'Thắng',
      cqLosers: 'Thua',
      cqDraw: 'Hoà',

      // ── winLossStats.html ──
      winLossStats: 'Thống kê Thắng/Thua',
      wlTotalCustomers: 'Tổng khách',
      wlWinners: 'Khách thắng',
      wlLosers: 'Khách thua',
      wlCompanyProfit: 'Lợi nhuận CT',
      wlTotalWon: 'Tổng thắng',
      wlTotalLost: 'Tổng thua',
      wlTopWinners: 'Top khách thắng (CT lỗ)',
      wlTopLosers: 'Top khách thua (CT lời)',
      wlByAgent: 'Thắng/Thua theo đại lý',

      // ── lotteryAnalysis.html ──
      lotteryAnalysis: 'Phân tích Xổ số',
      laTotalLotteries: 'Tổng loại XS',
      laTotalBet: 'Tổng cược',
      laTotalWL: 'Tổng T/T',
      laLotteryName: 'Loại XS',
      laPlayers: 'Người chơi',
      laBetCount: 'Lượt cược',
      laBetAmount: 'Cược',
      laValidAmount: 'Hợp lệ',
      laPrize: 'Thưởng',
      laRebateAmount: 'Hoàn trả',
      laWinLose: 'T/T',
      laCompanyProfit: 'Lợi nhuận CT',

      // ── detailedGameStats.html ──
      detailedGameStats: 'Thống kê Game Chi tiết',
      dgTotalGames: 'Tổng game',
      dgTotalBetCount: 'Tổng lượt cược',
      dgTotalBet: 'Tổng cược',
      dgGameName: 'Game',
      dgProvider: 'NCC',
      dgPlayers: 'Người chơi',
      dgBetCount: 'Lượt cược',
      dgBetAmount: 'Cược',
      dgTurnover: 'Doanh thu',
      dgPrize: 'Thưởng',
      dgWinLose: 'T/T',
      dgCompanyProfit: 'CT Profit',
      dgSearchGame: 'Tìm theo tên game...',

      // ── customerStatus.html ──
      customerStatus: 'Tình trạng Khách hàng',
      csPotential: 'Tiềm năng',
      csNeedCare: 'Cần chăm sóc',
      csNormal: 'Thường',
      csNew: 'Mới',
      csCategory: 'Phân loại',
      csActualProfit: 'Lợi nhuận thực',
      csCustomerList: 'Danh sách khách hàng',

      // ── providerAnalysis.html ──
      providerAnalysis: 'Phân tích NCC Game',
      paTotalProviders: 'Tổng NCC',
      paTotalBet: 'Tổng cược',
      paTotalWL: 'Tổng T/T',
      paProvider: 'Nhà cung cấp',
      paPlayers: 'Người chơi',
      paBetAmount: 'Cược',
      paBetTimes: 'Lượt cược',
      paWinLose: 'T/T',
      paCompanyProfit: 'Lợi nhuận CT',
      paTopGames: 'Top Games',
      paGameName: 'Game',
      paBetCount: 'Lượt cược'
    },

    en: {
      // ── Page titles ──
      adminPageTitle: 'Agent Hub — Admin',
      loginPageTitle: 'Agent Hub — Login',

      // ── Header ──
      toggleMenu: 'Toggle menu',
      reload: 'Reload page',
      fullscreen: 'Fullscreen',
      language: 'Language',
      changeLoginPw: 'Change login password',
      changeFundPw: 'Change fund password',
      logout: 'Logout',
      options: 'Options',
      noOptions: 'No options available.',

      // ── Sidebar ──
      memberMgmt: 'Member Management',
      members: 'Members',
      generalFeatures: 'General Features',
      revenueCalc: 'Revenue Calculation',
      promotionAnalysis: 'Promotion Analysis',
      customerQuality: 'Customer Quality',
      qcGroupQuality: 'QC Group Quality',
      qcTotalGroups: 'Total Groups',
      qcTotalMembers: 'Total Members',
      qcActiveMembers: 'Active',
      qcTotalDeposit: 'Total Deposit',
      qcGroup: 'Group',
      qcMembers: 'Members',
      qcActive: 'Active',
      dbLotteryBet: 'Lottery Bet',
      dbThirdBet: '3rd Party Bet',
      agentReport: 'Agent Detail Report',
      comingSoon: 'Coming soon...',
      referralCode: 'Referral Code',
      reports: 'Reports',
      lotteryReport: 'Lottery Report',
      transStatement: 'Transaction Statement',
      providerReport: 'Provider Report',
      commission: 'Commission',
      deposit: 'Deposit',
      withdraw: 'Withdraw',
      betOrders: 'Bet Orders',
      lotteryBet: 'Lottery Bet',
      thirdPartyBet: '3rd Party Bet',
      customer: 'Customer',
      rebateRate: 'Rebate Rate',
      management: 'Management',
      manageAgents: 'Manage Agents',
      manageUsers: 'Manage Users',

      // ── Tabs context ──
      closeTab: 'Close',
      closeOther: 'Close other tabs',
      closeRight: 'Close tabs to the right',
      closeAll: 'Close all',

      // ── Login ──
      loginTitle: 'Login',
      username: 'Username',
      password: 'Password',
      loginBtn: 'Login',
      loginSubtitle: 'Agent Management Hub',
      fillAllFields: 'Please fill in all fields',
      captchaPlaceholder: 'Captcha code',
      captchaClickRefresh: 'Click image to refresh',
      captchaWrong: 'Wrong captcha code',
      loginSuccess: 'Login successful!',
      loginFailed: 'Login failed',
      connectionError: 'Connection error',
      mustChangePwMsg:
        'You are using the default password. Please change it now to secure your account.',
      securityWarning: 'Security Warning',
      changePwNow: 'Change now',
      later: 'Later',

      // ── Common UI ──
      search: 'Search',
      reset: 'Reset',
      confirm: 'Confirm',
      submit: 'Submit',
      cancel: 'Cancel',
      select: 'Select',
      all: 'All',
      noData: 'No data',
      actions: 'Actions',
      edit: 'Edit',
      delete: 'Delete',
      active: 'Active',
      locked: 'Locked',
      stopped: 'Stopped',
      failed: 'Failed',
      updated: 'Updated',
      deleted: 'Deleted',
      error: 'Error',
      serverError: 'Server connection error',

      // ── Common data fields ──
      accountName: 'Account name',
      enterAccountName: 'Enter account name',
      serialNo: 'Transaction code',
      enterSerialNo: 'Enter transaction code',
      account: 'Account',
      agent: 'Agent',
      amount: 'Amount',
      trueAmount: 'Actual amount',
      createTime: 'Created time',
      updateTime: 'Updated',
      status: 'Status',
      time: 'Time',
      id: 'ID',
      uid: 'UID',
      agentId: 'Agent ID',
      agentTree: 'Agent tree',
      groupId: 'Group',
      remark: 'Remark',

      // ── Date filters ──
      today: 'Today',
      yesterday: 'Yesterday',
      thisWeek: 'This week',
      thisMonth: 'This month',
      lastMonth: 'Last month',
      dateStartEnd: 'Pick date range',
      dateStartEndTime: 'Pick date range',
      summaryData: 'Summary data:',

      // ── Status values ──
      statusPending: 'Pending',
      statusDone: 'Completed',
      statusProcessing: 'Processing',
      statusFailed: 'Failed',
      statusNotEval: 'Not evaluated',
      statusNormal: 'Normal',
      statusFrozen: 'Frozen',
      statusWait: 'Waiting',

      // ── Financial columns ──
      operator: 'Operator',
      successTime: 'Completed time',
      firmFee: 'Company fee',
      userFee: 'User fee',
      rebate: 'Rebate',
      accountHolder: 'Account holder',
      accountHolderShort: 'Account holder',
      bankId: 'Bank',
      branch: 'Branch',
      accountNo: 'Account number',
      transferTime: 'Transfer time',
      userRemark: 'User remark',
      proStatus: 'Processing status',
      prizeAmount: 'Prize amount',
      activityId: 'Promotion ID',
      extraInfo: 'Extra info',
      categoryId: 'Category',
      merchantId: 'Provider',
      payType: 'Payment type',
      tradeId: 'Payment code',
      isTester: 'Test account',
      reviewTime: 'Review time',
      transferRecord: 'Transfer record',
      currency: 'Currency',
      balance: 'Balance',
      betAmount: 'Bet amount',
      turnover: 'Turnover',
      prize: 'Prize',
      winLose: 'Win / Lose',
      result: 'Result',
      rebateAmount: 'Rebate',
      betTimes: 'Bet count',
      validAmount: 'Valid bet',

      // ── user.html ──
      memberMgmtSub: 'Sub-member Management',
      addMemberBtn: 'Add Member',
      addAgentBtn: 'Add New Agent',
      setRebateBtn: 'Set Rebate',
      firstDepositTime: 'First deposit time',
      sortByField: 'Sort by field',
      sortDirection: 'Sort direction',
      sortDesc: 'Descending',
      sortAsc: 'Ascending',
      memberType: 'Member type',
      agentAccount: 'Agent account',
      member: 'Member',
      depositCount: 'Deposits',
      withdrawCount: 'Withdrawals',
      totalDeposit: 'Total deposits',
      totalWithdraw: 'Total withdrawals',
      lastLoginTime: 'Last login',
      registerTime: 'Registration time',
      truename: 'Full name',
      phone: 'Phone',
      email: 'Email',
      inviteCode: 'Invite code',
      device: 'Device',
      loginIp: 'Login IP',
      level: 'Level',
      agentType: 'Agent type',
      phoneVerified: 'Phone verified',
      emailVerified: 'Email verified',
      userAgent: 'User Agent',
      lastUpdate: 'Last update',
      noteExtra: 'Extra notes',
      addNewAgent: 'Add new agent',
      addNewMember: 'Add new member',
      confirmPw: 'Confirm password',
      passwordNoMatch: 'Passwords do not match',
      agentAdded: 'Agent added',
      memberAdded: 'Member added',
      rebateTitle: 'Rebate rate',
      rebateUpdated: 'Rebate updated',
      rebateSetup: 'Rebate setup — ',
      chars416: '4-16 characters',
      chars620: '6-20 characters',
      retypePw: 'Re-enter password',

      // ── inviteList.html ──
      addInviteBtn: 'Add referral code',
      copyLink: 'Copy link',
      viewConfig: 'View settings',
      qrCode: 'QR Code',
      editBtn: 'Edit',
      addedTime: 'Added time',
      memberLoginTime: 'Member login time',
      enterInviteCode: 'Enter full referral code',
      inviteType: 'Referral type',
      totalRegistered: 'Total registered',
      registeredUsers: 'Registered users',
      rechargeCount: 'Recharge count',
      firstRechargeDay: 'First deposit today',
      registerRechargeDay: 'First deposit on registration day',
      rebateArr: 'Rebate',
      copied: 'Copied: ',
      configType: 'Type',
      notConfigured: 'Not configured',
      editInviteCode: 'Edit code: ',
      inviteDescription: 'Referral code description',
      inviteAdded: 'Referral code added',
      configTitle: 'Rebate settings — ',
      qrTitle: 'QR Code — ',

      // ── reportLottery.html ──
      reportLotteryTitle: 'Lottery Report',
      lotteryType: 'Lottery type',
      selectOrSearch: 'Select or type to search',
      bettersCount: 'Bettors',
      betCount: 'Bet count',
      validBetAmount: 'Valid bet amount (excl. draws)',
      winLoseNoRebate: 'Win/Lose result (excl. rebate)',
      prizeCol: 'Prize amount',
      lotteryName: 'Lottery type',
      lotteryId: 'Lottery ID',

      // ── reportFunds.html ──
      transStatementTitle: 'Transaction Statement',
      depositAmountTotal: 'Deposit amount',
      withdrawAmountTotal: 'Withdrawal amount',
      chargeFee: 'Service fee',
      agentCommission: 'Agent commission',
      promotion: 'Promotion',
      thirdRebate: '3rd party rebate',
      thirdActivityAmount: '3rd party bonus',
      depositCountCol: 'Deposit count',
      withdrawCountCol: 'Withdrawal count',
      dateCol: 'Date',

      // ── reportThirdGame.html ──
      reportThirdTitle: 'Game Provider Report',
      provider: 'Provider',
      betTimesCol: 'Bet count',
      bettersCountCol: 'Bettors',
      providerId: 'Provider ID',

      // ── depositAndWithdrawal.html ──
      depositWithdrawTitle: 'Deposit / Withdrawal Management',
      typeCol: 'Type',
      typeDeposit: 'Deposit',
      typeWithdraw: 'Withdrawal',

      // ── withdrawalsRecord.html ──
      withdrawHistoryTitle: 'Withdrawal History',
      statusFormat: 'Status',

      // ── bet.html ──
      betListTitle: 'Bet List',
      userName: 'Username',
      enterFullUsername: 'Enter full username',
      enterFullSerialNo: 'Enter full transaction code',
      game: 'Game',
      gameType: 'Game type',
      playStyle: 'Play style',
      betStatusUnpaid: 'Unpaid',
      betStatusWon: 'Won',
      betStatusLost: 'Lost',
      betStatusDraw: 'Draw',
      betStatusCancelUser: 'Cancelled by user',
      betStatusCancelSystem: 'Cancelled by system',
      betStatusAbnormal: 'Abnormal bet',
      betStatusUnpaidManual: 'Unpaid (manual restore)',
      betTime: 'Bet time',
      issue: 'Issue',
      betContent: 'Bet info',
      betMoney: 'Bet amount',
      betRebate: 'Rebate amount',
      betResult: 'Win/Lose',
      totalBetMoney: 'Bet amount',
      totalRebateAmount: 'Rebate amount',
      totalWinLose: 'Win/Lose',

      // ── betOrder.html ──
      thirdPartyBetTitle: '3rd Party Bet Orders',
      betTimeLabel: 'Bet time',
      platformAccount: 'Platform account',
      enterPlatformAccount: 'Enter account',
      gameCategory: 'Game category',
      gameName: 'Game name',
      tkPlatform: 'Platform account',
      categoryTypeId: 'Category ID',

      // ── editPassword.html ──
      editPwTitle: 'Change Login Password',
      oldPw: 'Old password',
      enterOldPw: 'Enter old password',
      newPassword: 'New password',
      confirmNewPw: 'Confirm new password',
      enterConfirmNewPw: 'Enter confirmation password',
      pwMismatch: 'New password and confirmation do not match',
      pwChangeSuccess: 'Password changed successfully',
      pwChangeFailed: 'Password change failed',

      // ── editFundPassword.html ──
      editFundPwTitle: 'Change Fund Password',
      fundPwOldHint: 'Fund password not set yet, leave empty as default',
      fundPwChangeSuccess: 'Fund password changed successfully',
      fundPwChangeFailed: 'Password change failed',

      // ── getRebateOddsPanel.html ──
      rebateOddsTitle: 'Rebate Rate',

      // ── admin.html (header dropdown) ──
      accountInfo: 'Account Info',
      settings: 'Settings',

      // ── manageAgents.html ──
      manageAgentsTitle: 'Manage EE88 Agent Accounts',
      solverOn: 'OCR: ON',
      solverOff: 'OCR: OFF',
      baseUrlLabel: 'Base URL',
      addAgentMgmt: 'Add Agent',
      checkAll: 'Check all',
      check: 'Check',
      login: 'Login',
      agentLabel: 'Agent name',
      baseUrl: 'URL',
      cookie: 'Cookie',
      ee88Account: 'EE88 Account',
      ee88NotConfigured: 'Not configured',
      users: 'Users',
      lastLoginCol: 'Last login',
      lastCheck: 'Last check',
      noAgents: 'No agents found',
      confirmDeleteAgent: 'Confirm delete agent "',
      deleteAgentPrompt: 'Choose how to handle this agent:',
      disableAgent: 'Disable',
      deleteAgentFull: 'Delete permanently',
      disableAgentHint: 'Disable: keep data, reactivate anytime',
      confirmHardDelete:
        'Permanent delete will remove the agent AND all synced data. Cannot be undone!',
      disabled: 'Disabled',
      enable: 'Enable',
      deleteData: 'Delete data',
      agentEnabled: 'Agent re-enabled',
      agentOk: 'Agent is working normally',
      agentProblem: 'Agent has issues',
      addNewAgentMgmt: 'Add New Agent',
      editAgentTitle: 'Edit agent: ',
      autoLoginSection: 'Auto-login EE88 (optional)',
      ee88Username: 'EE88 username',
      ee88Password: 'EE88 password',
      keepEmpty: 'Leave empty = keep current',
      cookieHint: 'PHPSESSID=xxx (leave empty for auto-login)',
      agentExample: 'E.g. Agent 1',
      mgmtAgentAdded: 'Agent added',
      loginConfirmMsg: 'Auto-login agent "',
      loginProcessHint: 'This may take 30-60 seconds',
      agentLoginSuccess: 'Login successful',
      agentLoginFailed: 'Login failed',
      agentsWorking: ' agents working',

      // ── manageUsers.html ──
      manageUsersTitle: 'Manage Hub Accounts',
      roleAdmin: 'Admin',
      roleUser: 'User',
      addUserBtn: 'Add User',
      permissions: 'Permissions',
      displayName: 'Display name',
      role: 'Role',
      assignedAgents: 'Assigned agents',
      allAdmin: 'All (admin)',
      noPermission: 'No permissions',
      createdAt: 'Created',
      noUsers: 'No users found',
      confirmDeleteUser: 'Confirm delete user "',
      addNewUser: 'Add New User',
      editUserTitle: 'Edit user: ',
      newPwLabel: 'New password',
      keepEmptyPw: 'Leave empty to keep current',
      minChars6: 'At least 6 characters',
      userAdded: 'User added',
      adminAllAccess: 'Admin has access to all agents',
      selectAgentAccess: 'Select agents that user ',
      selectAgentAccessSuffix: ' can access:',
      noAgentYet: 'No agents yet',
      savePermissions: 'Save permissions',
      permTitle: 'Permissions — ',
      permUpdated: 'Permissions updated',

      // ── Column Permissions ──
      columnPerm: 'Column Perm',
      columnPermTitle: 'Column Permissions',
      columnPermDesc: 'Configure visible columns for user',
      columnPermSaved: 'Column permissions saved',
      adminAllColumns: 'Admin always sees all columns',
      deselectAll: 'Deselect all',
      page_members: 'Members',
      page_reportLottery: 'Lottery Report',
      page_reportFunds: 'Funds Report',
      page_reportThirdGame: 'Provider Report',
      page_betOrder: 'Bet Orders',
      page_bet: 'Lottery Bets',
      page_withdrawals: 'Withdrawals',
      page_deposits: 'Deposits',
      page_inviteList: 'Invite List',
      page_dashboard: 'Dashboard',
      page_agentReport: 'Agent Report',
      page_customerStatus: 'Customer Status',
      page_customerRetention: 'Retention',
      page_winLossStats: 'Win/Loss',
      page_providerAnalysis: 'Provider Analysis',
      page_lotteryAnalysis: 'Lottery Analysis',
      page_depositWithdrawAnalysis: 'Deposit/Withdraw',
      page_promotionAnalysis: 'Promotion',
      page_financialSummary: 'Financial Summary',
      page_detailedGameStats: 'Game Stats',
      page_qcGroupQuality: 'Group Quality',
      page_revenueCalc: 'Revenue Calc',

      // ── Export ──
      exportExcel: 'Export Excel',

      // ── Dashboard ──
      dashboard: 'Dashboard',
      dbActiveAgents: 'Active Agents',
      dbExpiredAgents: 'Expired Agents',
      dbTotalAgents: 'Total Agents',
      dbAgentStatus: 'Agent Status',
      dbLoginStats: 'Login Stats (7 days)',
      dbLoginSuccess: 'Success',
      dbLoginFail: 'Failed',
      dbRecentActivity: 'Recent Activity',
      dbDateRange: 'Date Range',
      dbPickDateRange: 'Pick date range',
      dbLast7Days: '7 Days',
      dbLast30Days: '30 Days',
      dbTotalMembers: 'Total Members',
      dbNewMembers: 'New Members',
      dbActiveMembers: 'Active Members',
      dbDepositTotal: 'Total Deposits',
      dbWithdrawTotal: 'Total Withdrawals',
      dbNetWinLoss: 'Net Win/Loss',
      dbDepositWithdrawTrend: 'Deposit / Withdrawal Trend',
      dbWinLossBreakdown: 'Win / Loss Breakdown',
      dbLotteryWL: 'Lottery',
      dbThirdPartyWL: '3rd Party',
      dbPerAgent: 'Per Agent Breakdown',
      dbFirstDeposit: 'First Deposit',
      dbOrders: 'orders',
      dbBetAmount: 'Total Bet',
      dbPrize: 'Total Prize',
      dbLoading: 'Loading...',
      dbError: 'Failed to load data',
      dbRetry: 'Retry',
      dbNet: 'Net',
      dbSale: 'Sale',
      dbAgentLine: 'Agent Line',
      dbTodayNewCustomers: 'New Customers Today',
      dbTodayLotteryBet: 'Lottery Bet Today',
      dbTodayThirdBet: '3rd Party Bet Today',
      dbMonthlyLotteryBet: 'Monthly Lottery Bet',
      dbMonthlyThirdBet: 'Monthly 3rd Party Bet',
      dbTodayDeposit: 'Deposit Today',
      dbMonthlyDeposit: 'Monthly Deposit',
      dbLotteryWLTotal: 'Total Lottery W/L',
      dbThirdWLTotal: 'Total 3rd Party W/L',

      // ── Activity Log ──
      activityLog: 'Activity Log',
      activityLogTitle: 'Activity Log',
      actionCol: 'Action',
      targetCol: 'Target',
      ipCol: 'IP',
      detailCol: 'Detail',
      filterAction: 'Filter action',
      filterUsername: 'Filter user',

      // ── Login All + History ──
      loginAllBtn: 'Login All',
      loginAllConfirm: 'Auto-login all expired agents?',
      loginAllDone: 'Login complete',
      loginHistory: 'History',
      loginHistoryTitle: 'Login History',
      attemptsCol: 'Attempts',
      durationCol: 'Duration (ms)',
      sourceCol: 'Source',
      triggeredByCol: 'Triggered by',
      errorCol: 'Error',
      successCol: 'Result',

      // ── realtimeMonitor.html ──
      rtMonitor: 'Realtime Monitor',
      rtPollingStatus: 'Status',
      rtNewCustomers: 'New Customers',
      rtLostCustomers: 'Lost Customers',
      rtWsConnections: 'WS Connections',
      rtRunning: 'Running',
      rtStopped: 'Stopped',
      rtInterval: 'Interval',
      rtStart: 'Start',
      rtStop: 'Stop',
      rtMarkAllRead: 'Mark All Read',
      rtClearAll: 'Clear All',
      rtAll: 'All',
      rtNewOnly: 'New',
      rtLostOnly: 'Lost',
      rtUnread: 'Unread',
      rtNoEvents: 'No events yet. Start polling to monitor.',
      rtNewCustomerDetected: 'New customer detected',
      rtLostCustomerDetected: 'Lost customer detected',
      rtParent: 'Agent',
      rtLastPoll: 'Last poll',
      rtMembers: 'Members',
      rtMarkedRead: 'All marked as read',
      rtConfirmClear: 'Clear all realtime events?',
      rtRedisOk: 'Redis connected',
      rtRedisOff: 'Redis disconnected',

      // ── syncStatus.html (Phase 6: Cache + Sync) ──
      syncStatus: 'Sync',
      syncStatusTitle: 'Sync Status',
      syncNow: 'Sync Now',
      clearCache: 'Delete selected account DB',
      cacheOverview: 'Cache Overview',
      totalCached: 'Total Entries',
      totalRows: 'Total Rows',
      lockedDays: 'Locked Days',
      lastSyncTime: 'Last Sync',
      syncLogs: 'Sync Logs',
      syncSuccess: 'Success',
      syncError: 'Error',
      syncPending: 'Pending',
      syncRunning: 'Running',
      endpoint: 'Endpoint',
      cachedDate: 'Cached Date',
      rowCount: 'Rows',
      noSyncData: 'No sync data yet',
      confirmSync: 'Start syncing data?',
      noSelection: 'No account selected',
      confirmClearCache: 'Confirm delete DB of selected accounts?',
      syncStarted: 'Sync started',
      cacheCleared: 'Selected account DB deleted',
      filterEndpoint: 'Filter endpoint',
      filterStatus: 'Filter status',
      filterAgent: 'Filter agent',
      selectAll: 'Select all',
      syncing: 'Syncing',
      cacheHit: 'Cache HIT',
      cacheMiss: 'Cache MISS',
      syncProgress: 'Progress',
      dateCount: 'Days',
      noSync: 'Not synced',
      totalAgents: 'Total Agents',
      fullySynced: 'Fully Synced',
      notSynced: 'Not synced',
      completed: 'Completed',
      pending: 'Pending',
      elapsed: 'Elapsed',
      ready: 'Ready',
      confirmClearLocks: 'Clear all day locks?',

      // ── Login (remember) ──
      saveAccount: 'Save account',

      // ── syncStatus.html additional ──
      syncDataTitle: 'Data Sync',
      syncBtn: 'Sync',
      clearLocksBtn: 'Clear Locks',
      syncAllBtn: 'Sync All',
      clearSelectedBtn: 'Clear Selected',
      agentDataType: 'Agent / Data Type',
      dataRows: 'Data Rows',
      lockedDaysCol: 'Locked Days',
      syncingIndicator: 'Syncing...',
      confirmSyncAll: 'Sync all agents?',
      confirmSyncAgent: 'Sync',
      confirmClearAgentLocks: 'Clear all day locks for',
      confirmClearSelectedLocks: 'Clear day locks for',
      selectedAgents: 'selected agents',

      // ── Endpoint display names (syncStatus) ──
      epMembers: 'Member List',
      epInvites: 'Invite Codes',
      epBetOrders: '3rd Party Bets',
      epDeposits: 'Deposits / Withdrawals',
      epWithdrawals: 'Withdrawal History',
      epLotteryBets: 'Lottery Bets',
      epLotteryBetsSummary: 'Lottery Bets Summary',
      epReportLottery: 'Lottery Report',
      epReportFunds: 'Transaction Statement',
      epReportThird: 'Provider Report',

      // ── revenueCalc.html ──
      revTotalRevenue: 'Total Revenue',
      revLotteryProfit: 'Lottery Profit',
      revThirdProfit: '3rd Party Profit',
      revPerAgent: 'Per Agent Breakdown',
      revVsPrev: 'vs previous period',
      revNewPeriod: 'New period (no prior data)',

      // ── promotionAnalysis.html ──
      pmTotalPromotion: 'Total Promotion',
      pmTotalRebate: '3rd Party Rebate',
      pmTotalActivity: '3rd Party Activity',
      pmPromoRate: 'Promotion/Deposit Ratio',
      pmThirdActivity: '3rd Party Activity',
      pmRate: 'Rate (%)',

      // ── depositWithdrawAnalysis.html ──
      depositWithdrawAnalysis: 'Deposit/Withdrawal Analysis',
      dwTotalDeposit: 'Total Deposit',
      dwTotalWithdrawal: 'Total Withdrawal',
      dwNet: 'Net (Deposit - Withdrawal)',
      dwPromotion: 'Promotion',
      dwRebate: 'Rebate',
      dwDailyTrend: 'Daily Deposit/Withdrawal Trend',
      dwNetAmount: 'Net Amount',

      // ── financialSummary.html ──
      financialSummary: 'Financial Summary',
      fsTotalRevenue: 'Revenue',
      fsCost: 'Cost',
      fsProfit: 'Profit',
      fsMargin: 'Margin',
      fsLotteryWL: 'Lottery W/L',
      fsThirdWL: '3rd Party W/L',
      fsPerAgent: 'Per Agent Breakdown',

      // ── customerQuality.html ──
      cqTotalMembers: 'Total Members',
      cqActiveMembers: 'Active Members',
      cqInactiveMembers: 'Inactive Members',
      cqDepositRate: 'Deposit Rate',
      cqDepositTier: 'Deposit Tier',
      cqWinLossSeg: 'Win/Loss Segmentation',
      cqQualityMetrics: 'Quality Metrics',
      cqMultiDeposit: 'Multi-Deposit',
      cqMultiDepositDesc: 'Customers with 2+ deposits',
      cqHighValue: 'High Value (≥10M)',
      cqHighValueDesc: 'Total deposits ≥ 10 million',
      cqMultiDepositRate: 'Repeat Deposit Rate',
      cqMultiDepositRateDesc: 'Among depositing customers',
      cqTierZero: 'No Deposit (0)',
      cqTierUnder1M: 'Under 1M',
      cqTier1to5M: '1-5M',
      cqTier5to10M: '5-10M',
      cqTier10to50M: '10-50M',
      cqTierOver50M: 'Over 50M',
      cqWinners: 'Winners',
      cqLosers: 'Losers',
      cqDraw: 'Draw',

      // ── winLossStats.html ──
      winLossStats: 'Win/Loss Statistics',
      wlTotalCustomers: 'Total Customers',
      wlWinners: 'Winners',
      wlLosers: 'Losers',
      wlCompanyProfit: 'Company Profit',
      wlTotalWon: 'Total Won',
      wlTotalLost: 'Total Lost',
      wlTopWinners: 'Top Winners (Company Loss)',
      wlTopLosers: 'Top Losers (Company Profit)',
      wlByAgent: 'Win/Loss by Agent',

      // ── lotteryAnalysis.html ──
      lotteryAnalysis: 'Lottery Analysis',
      laTotalLotteries: 'Total Lotteries',
      laTotalBet: 'Total Bet',
      laTotalWL: 'Total W/L',
      laLotteryName: 'Lottery Type',
      laPlayers: 'Players',
      laBetCount: 'Bet Count',
      laBetAmount: 'Bet Amount',
      laValidAmount: 'Valid Amount',
      laPrize: 'Prize',
      laRebateAmount: 'Rebate',
      laWinLose: 'W/L',
      laCompanyProfit: 'Company Profit',

      // ── detailedGameStats.html ──
      detailedGameStats: 'Detailed Game Statistics',
      dgTotalGames: 'Total Games',
      dgTotalBetCount: 'Total Bet Count',
      dgTotalBet: 'Total Bet',
      dgGameName: 'Game',
      dgProvider: 'Provider',
      dgPlayers: 'Players',
      dgBetCount: 'Bet Count',
      dgBetAmount: 'Bet Amount',
      dgTurnover: 'Turnover',
      dgPrize: 'Prize',
      dgWinLose: 'W/L',
      dgCompanyProfit: 'Company Profit',
      dgSearchGame: 'Search by game name...',

      // ── customerStatus.html ──
      customerStatus: 'Customer Status',
      csPotential: 'Potential',
      csNeedCare: 'Needs Care',
      csNormal: 'Normal',
      csNew: 'New',
      csCategory: 'Category',
      csActualProfit: 'Actual Profit',
      csCustomerList: 'Customer List',

      // ── providerAnalysis.html ──
      providerAnalysis: 'Provider / Game Analysis',
      paTotalProviders: 'Total Providers',
      paTotalBet: 'Total Bet',
      paTotalWL: 'Total W/L',
      paProvider: 'Provider',
      paPlayers: 'Players',
      paBetAmount: 'Bet Amount',
      paBetTimes: 'Bet Times',
      paWinLose: 'W/L',
      paCompanyProfit: 'Company Profit',
      paTopGames: 'Top Games',
      paGameName: 'Game',
      paBetCount: 'Bet Count'
    },

    'zh-CN': {
      // ── Page titles ──
      adminPageTitle: 'Agent Hub — 管理',
      loginPageTitle: 'Agent Hub — 登录',

      // ── Header ──
      toggleMenu: '折叠菜单',
      reload: '刷新页面',
      fullscreen: '全屏',
      language: '语言',
      changeLoginPw: '修改登录密码',
      changeFundPw: '修改资金密码',
      logout: '退出登录',
      options: '选项',
      noOptions: '暂无选项。',

      // ── Sidebar ──
      memberMgmt: '会员管理',
      members: '会员',
      generalFeatures: '常用功能',
      revenueCalc: '营收计算',
      promotionAnalysis: '优惠分析',
      customerQuality: '客户质量',
      qcGroupQuality: 'QC组质量',
      qcTotalGroups: '总组数',
      qcTotalMembers: '总成员',
      qcActiveMembers: '活跃',
      qcTotalDeposit: '总充值',
      qcGroup: '组',
      qcMembers: '成员',
      qcActive: '活跃',
      dbLotteryBet: '彩票投注',
      dbThirdBet: '三方投注',
      agentReport: '代理详细报表',
      comingSoon: '功能开发中...',
      referralCode: '邀请码',
      reports: '报表',
      lotteryReport: '彩票报表',
      transStatement: '交易流水',
      providerReport: '供应商报表',
      commission: '佣金提取',
      deposit: '充值',
      withdraw: '提现',
      betOrders: '投注单',
      lotteryBet: '彩票投注',
      thirdPartyBet: '第三方投注',
      customer: '客户',
      rebateRate: '返点比例',
      management: '管理',
      manageAgents: '代理管理',
      manageUsers: '用户管理',

      // ── Tabs context ──
      closeTab: '关闭',
      closeOther: '关闭其他标签',
      closeRight: '关闭右侧标签',
      closeAll: '关闭所有',

      // ── Login ──
      loginTitle: '登录',
      username: '用户名',
      password: '密码',
      loginBtn: '登录',
      loginSubtitle: '代理管理系统',
      fillAllFields: '请填写所有字段',
      captchaPlaceholder: '验证码',
      captchaClickRefresh: '点击图片刷新',
      captchaWrong: '验证码错误',
      loginSuccess: '登录成功！',
      loginFailed: '登录失败',
      connectionError: '连接错误',
      mustChangePwMsg: '您正在使用默认密码。请立即更改密码以保护您的账户安全。',
      securityWarning: '安全警告',
      changePwNow: '立即更改',
      later: '稍后',

      // ── Common UI ──
      search: '搜索',
      reset: '重置',
      confirm: '确认',
      submit: '提交',
      cancel: '取消',
      select: '选择',
      all: '全部',
      noData: '暂无数据',
      actions: '操作',
      edit: '编辑',
      delete: '删除',
      active: '活跃',
      locked: '锁定',
      stopped: '停用',
      failed: '失败',
      updated: '已更新',
      deleted: '已删除',
      error: '错误',
      serverError: '服务器连接错误',

      // ── Common data fields ──
      accountName: '账户名称',
      enterAccountName: '输入账户名称',
      serialNo: '交易编号',
      enterSerialNo: '输入交易编号',
      account: '账户',
      agent: '代理',
      amount: '金额',
      trueAmount: '实际金额',
      createTime: '创建时间',
      updateTime: '更新时间',
      status: '状态',
      time: '时间',
      id: 'ID',
      uid: 'UID',
      agentId: '代理ID',
      agentTree: '代理树',
      groupId: '分组',
      remark: '备注',

      // ── Date filters ──
      today: '今天',
      yesterday: '昨天',
      thisWeek: '本周',
      thisMonth: '本月',
      lastMonth: '上月',
      dateStartEnd: '选择时间范围',
      dateStartEndTime: '选择时间范围',
      summaryData: '汇总数据：',

      // ── Status values ──
      statusPending: '待处理',
      statusDone: '已完成',
      statusProcessing: '处理中',
      statusFailed: '失败',
      statusNotEval: '未评估',
      statusNormal: '正常',
      statusFrozen: '冻结',
      statusWait: '等待',

      // ── Financial columns ──
      operator: '操作员',
      successTime: '完成时间',
      firmFee: '公司费用',
      userFee: '用户费用',
      rebate: '返点',
      accountHolder: '户主',
      accountHolderShort: '户主',
      bankId: '银行',
      branch: '支行',
      accountNo: '账号',
      transferTime: '转账时间',
      userRemark: '用户备注',
      proStatus: '处理状态',
      prizeAmount: '奖金',
      activityId: '活动ID',
      extraInfo: '附加信息',
      categoryId: '分类',
      merchantId: '供应商',
      payType: '支付方式',
      tradeId: '支付编号',
      isTester: '测试账户',
      reviewTime: '审核时间',
      transferRecord: '转账记录',
      currency: '货币',
      balance: '余额',
      betAmount: '投注金额',
      turnover: '流水',
      prize: '中奖',
      winLose: '输赢',
      result: '结果',
      rebateAmount: '返点',
      betTimes: '投注次数',
      validAmount: '有效投注',

      // ── user.html ──
      memberMgmtSub: '下级会员管理',
      addMemberBtn: '添加会员',
      addAgentBtn: '新增代理',
      setRebateBtn: '设置返点',
      firstDepositTime: '首充时间',
      sortByField: '排序字段',
      sortDirection: '排序方向',
      sortDesc: '降序',
      sortAsc: '升序',
      memberType: '会员类型',
      agentAccount: '代理账户',
      member: '会员',
      depositCount: '充值次数',
      withdrawCount: '提现次数',
      totalDeposit: '充值总额',
      totalWithdraw: '提现总额',
      lastLoginTime: '最后登录',
      registerTime: '注册时间',
      truename: '姓名',
      phone: '电话',
      email: '邮箱',
      inviteCode: '邀请码',
      device: '设备',
      loginIp: '登录IP',
      level: '等级',
      agentType: '代理类型',
      phoneVerified: '手机验证',
      emailVerified: '邮箱验证',
      userAgent: 'User Agent',
      lastUpdate: '最后更新',
      noteExtra: '额外备注',
      addNewAgent: '添加新代理',
      addNewMember: '添加新会员',
      confirmPw: '确认密码',
      passwordNoMatch: '密码不匹配',
      agentAdded: '已添加代理',
      memberAdded: '已添加会员',
      rebateTitle: '返点比例',
      rebateUpdated: '已更新返点',
      rebateSetup: '设置返点 — ',
      chars416: '4-16个字符',
      chars620: '6-20个字符',
      retypePw: '重新输入密码',

      // ── inviteList.html ──
      addInviteBtn: '添加邀请码',
      copyLink: '复制链接',
      viewConfig: '查看设置',
      qrCode: '二维码',
      editBtn: '编辑',
      addedTime: '添加时间',
      memberLoginTime: '会员登录时间',
      enterInviteCode: '输入完整邀请码',
      inviteType: '邀请类型',
      totalRegistered: '注册总数',
      registeredUsers: '已注册用户',
      rechargeCount: '充值人数',
      firstRechargeDay: '当日首充',
      registerRechargeDay: '注册日首充',
      rebateArr: '返点',
      copied: '已复制：',
      configType: '类型',
      notConfigured: '未配置',
      editInviteCode: '编辑邀请码：',
      inviteDescription: '邀请码描述',
      inviteAdded: '已添加邀请码',
      configTitle: '返点设置 — ',
      qrTitle: '二维码 — ',

      // ── reportLottery.html ──
      reportLotteryTitle: '彩票报表',
      lotteryType: '彩种名称',
      selectOrSearch: '选择或输入搜索',
      bettersCount: '投注人数',
      betCount: '投注次数',
      validBetAmount: '有效投注（不含和局）',
      winLoseNoRebate: '输赢结果（不含返点）',
      prizeCol: '中奖金额',
      lotteryName: '彩种',
      lotteryId: '彩种ID',

      // ── reportFunds.html ──
      transStatementTitle: '交易流水',
      depositAmountTotal: '充值金额',
      withdrawAmountTotal: '提现金额',
      chargeFee: '手续费',
      agentCommission: '代理佣金',
      promotion: '优惠',
      thirdRebate: '第三方返点',
      thirdActivityAmount: '第三方奖金',
      depositCountCol: '充值次数',
      withdrawCountCol: '提现次数',
      dateCol: '日期',

      // ── reportThirdGame.html ──
      reportThirdTitle: '游戏供应商报表',
      provider: '供应商',
      betTimesCol: '投注次数',
      bettersCountCol: '投注人数',
      providerId: '供应商ID',

      // ── depositAndWithdrawal.html ──
      depositWithdrawTitle: '充提管理',
      typeCol: '类型',
      typeDeposit: '充值',
      typeWithdraw: '提现',

      // ── withdrawalsRecord.html ──
      withdrawHistoryTitle: '提现记录',
      statusFormat: '状态',

      // ── bet.html ──
      betListTitle: '投注列表',
      userName: '用户名',
      enterFullUsername: '请输入完整用户名',
      enterFullSerialNo: '输入完整交易编号',
      game: '游戏',
      gameType: '游戏类型',
      playStyle: '玩法',
      betStatusUnpaid: '未结算',
      betStatusWon: '中奖',
      betStatusLost: '未中奖',
      betStatusDraw: '和局',
      betStatusCancelUser: '用户取消',
      betStatusCancelSystem: '系统取消',
      betStatusAbnormal: '异常投注',
      betStatusUnpaidManual: '未结算（手动恢复）',
      betTime: '投注时间',
      issue: '期号',
      betContent: '投注信息',
      betMoney: '投注金额',
      betRebate: '返点金额',
      betResult: '输赢',
      totalBetMoney: '投注金额',
      totalRebateAmount: '返点金额',
      totalWinLose: '输赢',

      // ── betOrder.html ──
      thirdPartyBetTitle: '第三方投注单',
      betTimeLabel: '投注时间',
      platformAccount: '平台账户',
      enterPlatformAccount: '输入账户',
      gameCategory: '游戏分类',
      gameName: '游戏名称',
      tkPlatform: '平台账户',
      categoryTypeId: '分类ID',

      // ── editPassword.html ──
      editPwTitle: '修改登录密码',
      oldPw: '旧密码',
      enterOldPw: '输入旧密码',
      newPassword: '新密码',
      confirmNewPw: '确认新密码',
      enterConfirmNewPw: '输入确认密码',
      pwMismatch: '新密码与确认密码不匹配',
      pwChangeSuccess: '密码修改成功',
      pwChangeFailed: '密码修改失败',

      // ── editFundPassword.html ──
      editFundPwTitle: '修改资金密码',
      fundPwOldHint: '未设置资金密码，默认留空',
      fundPwChangeSuccess: '资金密码修改成功',
      fundPwChangeFailed: '密码修改失败',

      // ── getRebateOddsPanel.html ──
      rebateOddsTitle: '返点比例',

      // ── admin.html (header dropdown) ──
      accountInfo: '账户信息',
      settings: '设置',

      // ── manageAgents.html ──
      manageAgentsTitle: '管理EE88代理账户',
      solverOn: 'OCR: 开启',
      solverOff: 'OCR: 关闭',
      baseUrlLabel: 'Base URL',
      addAgentMgmt: '添加代理',
      checkAll: '检查全部',
      check: '检查',
      login: '登录',
      agentLabel: '代理名称',
      baseUrl: 'URL',
      cookie: 'Cookie',
      ee88Account: 'EE88账户',
      ee88NotConfigured: '未配置',
      users: '用户',
      lastLoginCol: '最后登录',
      lastCheck: '最后检查',
      noAgents: '暂无代理',
      confirmDeleteAgent: '确认删除代理"',
      deleteAgentPrompt: '选择如何处理此代理：',
      disableAgent: '禁用',
      deleteAgentFull: '彻底删除',
      disableAgentHint: '禁用：保留数据，随时可重新启用',
      confirmHardDelete: '彻底删除将删除代理及所有同步数据，无法恢复！',
      disabled: '已禁用',
      enable: '启用',
      deleteData: '删除数据',
      agentEnabled: '已重新启用代理',
      agentOk: '代理运行正常',
      agentProblem: '代理有问题',
      addNewAgentMgmt: '添加新代理',
      editAgentTitle: '编辑代理：',
      autoLoginSection: '自动登录EE88（可选）',
      ee88Username: 'EE88用户名',
      ee88Password: 'EE88密码',
      keepEmpty: '留空=保持不变',
      cookieHint: 'PHPSESSID=xxx（留空使用自动登录）',
      agentExample: '例如：代理1',
      mgmtAgentAdded: '已添加代理',
      loginConfirmMsg: '自动登录代理"',
      loginProcessHint: '此过程可能需要30-60秒',
      agentLoginSuccess: '登录成功',
      agentLoginFailed: '登录失败',
      agentsWorking: '个代理正常运行',

      // ── manageUsers.html ──
      manageUsersTitle: '管理Hub账户',
      roleAdmin: 'Admin',
      roleUser: 'User',
      addUserBtn: '添加用户',
      permissions: '权限',
      displayName: '显示名称',
      role: '角色',
      assignedAgents: '已分配代理',
      allAdmin: '全部（管理员）',
      noPermission: '未分配权限',
      createdAt: '创建时间',
      noUsers: '暂无用户',
      confirmDeleteUser: '确认删除用户"',
      addNewUser: '添加新用户',
      editUserTitle: '编辑用户：',
      newPwLabel: '新密码',
      keepEmptyPw: '留空不修改',
      minChars6: '至少6个字符',
      userAdded: '已添加用户',
      adminAllAccess: '管理员有权访问所有代理',
      selectAgentAccess: '选择用户',
      selectAgentAccessSuffix: '可访问的代理：',
      noAgentYet: '暂无代理',
      savePermissions: '保存权限',
      permTitle: '权限 — ',
      permUpdated: '已更新权限',

      // ── Column Permissions ──
      columnPerm: '列权限',
      columnPermTitle: '列权限',
      columnPermDesc: '配置用户可见列',
      columnPermSaved: '列权限已保存',
      adminAllColumns: '管理员始终可见所有列',
      deselectAll: '取消全选',
      page_members: '会员',
      page_reportLottery: '彩票报表',
      page_reportFunds: '资金报表',
      page_reportThirdGame: '供应商报表',
      page_betOrder: '投注订单',
      page_bet: '彩票投注',
      page_withdrawals: '提款',
      page_deposits: '充值',
      page_inviteList: '邀请列表',
      page_dashboard: '仪表盘',
      page_agentReport: '代理报表',
      page_customerStatus: '客户分类',
      page_customerRetention: '客户留存',
      page_winLossStats: '输赢统计',
      page_providerAnalysis: '供应商分析',
      page_lotteryAnalysis: '彩票分析',
      page_depositWithdrawAnalysis: '充提分析',
      page_promotionAnalysis: '优惠分析',
      page_financialSummary: '财务汇总',
      page_detailedGameStats: '游戏统计',
      page_qcGroupQuality: '群组质量',
      page_revenueCalc: '营收计算',

      // ── Export ──
      exportExcel: '导出Excel',

      // ── Dashboard ──
      dashboard: '仪表盘',
      dbActiveAgents: '活跃代理',
      dbExpiredAgents: '过期代理',
      dbTotalAgents: '代理总数',
      dbAgentStatus: '代理状态',
      dbLoginStats: '登录统计（7天）',
      dbLoginSuccess: '成功',
      dbLoginFail: '失败',
      dbRecentActivity: '近期活动',
      dbDateRange: '时间范围',
      dbPickDateRange: '选择时间范围',
      dbLast7Days: '7天',
      dbLast30Days: '30天',
      dbTotalMembers: '会员总数',
      dbNewMembers: '新增会员',
      dbActiveMembers: '活跃会员',
      dbDepositTotal: '充值总额',
      dbWithdrawTotal: '提现总额',
      dbNetWinLoss: '净输赢',
      dbDepositWithdrawTrend: '充提趋势',
      dbWinLossBreakdown: '输赢分布',
      dbLotteryWL: '彩票',
      dbThirdPartyWL: '第三方',
      dbPerAgent: '代理明细',
      dbFirstDeposit: '首充',
      dbOrders: '笔',
      dbBetAmount: '总投注',
      dbPrize: '总奖金',
      dbLoading: '加载中...',
      dbError: '加载数据失败',
      dbRetry: '重试',
      dbNet: '净额',
      dbSale: '推广',
      dbAgentLine: '代理线',
      dbTodayNewCustomers: '今日开发客户数量',
      dbTodayLotteryBet: '今日彩票投注金额',
      dbTodayThirdBet: '今日三方投注金额',
      dbMonthlyLotteryBet: '本月彩票投注总金额',
      dbMonthlyThirdBet: '本月三方投注总金额',
      dbTodayDeposit: '当日充值金额',
      dbMonthlyDeposit: '本月充值总金额',
      dbLotteryWLTotal: '彩票总输赢',
      dbThirdWLTotal: '三方总输赢',

      // ── Activity Log ──
      activityLog: '活动日志',
      activityLogTitle: '活动日志',
      actionCol: '操作',
      targetCol: '对象',
      ipCol: 'IP',
      detailCol: '详情',
      filterAction: '筛选操作',
      filterUsername: '筛选用户',

      // ── Login All + History ──
      loginAllBtn: '全部登录',
      loginAllConfirm: '自动登录所有过期代理？',
      loginAllDone: '登录完成',
      loginHistory: '历史',
      loginHistoryTitle: '登录历史',
      attemptsCol: '尝试次数',
      durationCol: '耗时（毫秒）',
      sourceCol: '来源',
      triggeredByCol: '触发者',
      errorCol: '错误',
      successCol: '结果',

      // ── realtimeMonitor.html ──
      rtMonitor: '实时监控',
      rtPollingStatus: '状态',
      rtNewCustomers: '新客户',
      rtLostCustomers: '流失客户',
      rtWsConnections: 'WS连接数',
      rtRunning: '运行中',
      rtStopped: '已停止',
      rtInterval: '间隔',
      rtStart: '开始',
      rtStop: '停止',
      rtMarkAllRead: '全部已读',
      rtClearAll: '全部清除',
      rtAll: '全部',
      rtNewOnly: '新客户',
      rtLostOnly: '流失客户',
      rtUnread: '未读',
      rtNoEvents: '暂无事件。开始轮询以进行监控。',
      rtNewCustomerDetected: '检测到新客户',
      rtLostCustomerDetected: '检测到客户流失',
      rtParent: '代理',
      rtLastPoll: '最后轮询',
      rtMembers: '会员',
      rtMarkedRead: '全部标记为已读',
      rtConfirmClear: '清除所有实时事件？',
      rtRedisOk: 'Redis已连接',
      rtRedisOff: 'Redis未连接',

      // ── syncStatus.html (Phase 6: Cache + Sync) ──
      syncStatus: '同步',
      syncStatusTitle: '同步状态',
      syncNow: '立即同步',
      clearCache: '删除已选账户数据库',
      cacheOverview: '缓存概览',
      totalCached: '总记录数',
      totalRows: '总数据行',
      lockedDays: '已锁定天数',
      lastSyncTime: '上次同步',
      syncLogs: '同步日志',
      syncSuccess: '成功',
      syncError: '错误',
      syncPending: '等待',
      syncRunning: '运行中',
      endpoint: '接口',
      cachedDate: '缓存日期',
      rowCount: '行数',
      noSyncData: '暂无同步数据',
      confirmSync: '开始同步数据？',
      noSelection: '未选择任何账户',
      confirmClearCache: '确认删除已选账户的数据库？',
      syncStarted: '同步已开始',
      cacheCleared: '已删除已选账户数据库',
      filterEndpoint: '筛选接口',
      filterStatus: '筛选状态',
      filterAgent: '筛选代理',
      selectAll: '全选',
      syncing: '同步中',
      cacheHit: '缓存命中',
      cacheMiss: '缓存未命中',
      syncProgress: '进度',
      dateCount: '天数',
      noSync: '未同步',
      totalAgents: '总代理',
      fullySynced: '完全同步',
      notSynced: '未同步',
      completed: '完成',
      pending: '等待',
      elapsed: '耗时',
      ready: '就绪',
      confirmClearLocks: '清除所有日锁定？',

      // ── Login (remember) ──
      saveAccount: '保存账号',

      // ── syncStatus.html additional ──
      syncDataTitle: '数据同步',
      syncBtn: '同步',
      clearLocksBtn: '清除锁定',
      syncAllBtn: '全部同步',
      clearSelectedBtn: '清除已选锁定',
      agentDataType: '代理 / 数据类型',
      dataRows: '数据行',
      lockedDaysCol: '锁定天数',
      syncingIndicator: '同步中...',
      confirmSyncAll: '同步所有代理？',
      confirmSyncAgent: '同步',
      confirmClearAgentLocks: '清除所有日锁定',
      confirmClearSelectedLocks: '清除日锁定',
      selectedAgents: '个已选代理',

      // ── Endpoint display names (syncStatus) ──
      epMembers: '会员列表',
      epInvites: '邀请码',
      epBetOrders: '第三方投注',
      epDeposits: '充提',
      epWithdrawals: '提现记录',
      epLotteryBets: '彩票投注',
      epLotteryBetsSummary: '彩票投注汇总',
      epReportLottery: '彩票报表',
      epReportFunds: '交易流水',
      epReportThird: '供应商报表',

      // ── revenueCalc.html ──
      revTotalRevenue: '总营收',
      revLotteryProfit: '彩票利润',
      revThirdProfit: '第三方利润',
      revPerAgent: '代理明细',
      revVsPrev: '对比上期',
      revNewPeriod: '新期间（无前期数据）',

      // ── promotionAnalysis.html ──
      pmTotalPromotion: '总优惠',
      pmTotalRebate: '第三方返点',
      pmTotalActivity: '第三方活动',
      pmPromoRate: '优惠/充值比',
      pmThirdActivity: '第三方活动',
      pmRate: '比率 (%)',

      // ── depositWithdrawAnalysis.html ──
      depositWithdrawAnalysis: '充提分析',
      dwTotalDeposit: '总充值',
      dwTotalWithdrawal: '总提现',
      dwNet: '净额（充值 - 提现）',
      dwPromotion: '优惠',
      dwRebate: '返点',
      dwDailyTrend: '每日充提趋势',
      dwNetAmount: '净额',

      // ── financialSummary.html ──
      financialSummary: '财务汇总',
      fsTotalRevenue: '营收',
      fsCost: '成本',
      fsProfit: '利润',
      fsMargin: '利润率',
      fsLotteryWL: '彩票盈亏',
      fsThirdWL: '第三方盈亏',
      fsPerAgent: '代理明细',

      // ── customerQuality.html ──
      cqTotalMembers: '会员总数',
      cqActiveMembers: '活跃会员',
      cqInactiveMembers: '不活跃会员',
      cqDepositRate: '充值率',
      cqDepositTier: '充值分级',
      cqWinLossSeg: '输赢分布',
      cqQualityMetrics: '质量指标',
      cqMultiDeposit: '多次充值',
      cqMultiDepositDesc: '充值2次以上的客户',
      cqHighValue: '高价值 (≥1000万)',
      cqHighValueDesc: '总充值≥1000万',
      cqMultiDepositRate: '复充率',
      cqMultiDepositRateDesc: '已充值客户中',
      cqTierZero: '未充值 (0)',
      cqTierUnder1M: '100万以下',
      cqTier1to5M: '100-500万',
      cqTier5to10M: '500-1000万',
      cqTier10to50M: '1000-5000万',
      cqTierOver50M: '5000万以上',
      cqWinners: '赢家',
      cqLosers: '输家',
      cqDraw: '平局',

      // ── winLossStats.html ──
      winLossStats: '输赢统计',
      wlTotalCustomers: '总客户',
      wlWinners: '赢家',
      wlLosers: '输家',
      wlCompanyProfit: '公司利润',
      wlTotalWon: '总赢金额',
      wlTotalLost: '总输金额',
      wlTopWinners: 'Top赢家（公司亏损）',
      wlTopLosers: 'Top输家（公司盈利）',
      wlByAgent: '代理输赢',

      // ── lotteryAnalysis.html ──
      lotteryAnalysis: '彩票分析',
      laTotalLotteries: '彩票类型总数',
      laTotalBet: '总投注',
      laTotalWL: '总输赢',
      laLotteryName: '彩票类型',
      laPlayers: '玩家',
      laBetCount: '投注次数',
      laBetAmount: '投注额',
      laValidAmount: '有效投注',
      laPrize: '奖金',
      laRebateAmount: '返水',
      laWinLose: '输赢',
      laCompanyProfit: '公司利润',

      // ── detailedGameStats.html ──
      detailedGameStats: '游戏详细统计',
      dgTotalGames: '游戏总数',
      dgTotalBetCount: '总投注次数',
      dgTotalBet: '总投注额',
      dgGameName: '游戏',
      dgProvider: '供应商',
      dgPlayers: '玩家',
      dgBetCount: '投注次数',
      dgBetAmount: '投注额',
      dgTurnover: '流水',
      dgPrize: '奖金',
      dgWinLose: '输赢',
      dgCompanyProfit: '公司利润',
      dgSearchGame: '按游戏名搜索...',

      // ── customerStatus.html ──
      customerStatus: '客户状态',
      csPotential: '潜力客户',
      csNeedCare: '需关注',
      csNormal: '普通',
      csNew: '新客户',
      csCategory: '分类',
      csActualProfit: '实际利润',
      csCustomerList: '客户列表',

      // ── providerAnalysis.html ──
      providerAnalysis: '供应商游戏分析',
      paTotalProviders: '总供应商',
      paTotalBet: '总投注',
      paTotalWL: '总输赢',
      paProvider: '供应商',
      paPlayers: '玩家',
      paBetAmount: '投注额',
      paBetTimes: '投注次数',
      paWinLose: '输赢',
      paCompanyProfit: '公司利润',
      paTopGames: 'Top游戏',
      paGameName: '游戏',
      paBetCount: '投注次数'
    }
  };

  // ── Layui component messages (override zh-CN default) ──
  var layuiMessages = {
    vi: {
      form: {
        select: {
          noData: 'Không có dữ liệu',
          noMatch: 'Không tìm thấy',
          placeholder: 'Vui lòng chọn'
        },
        validateMessages: {
          required: 'Không được để trống',
          phone: 'Số điện thoại không đúng',
          email: 'Email không đúng',
          url: 'Đường dẫn không đúng',
          number: 'Chỉ được nhập số',
          date: 'Ngày tháng không đúng',
          identity: 'Số CMND không đúng'
        },
        verifyErrorPromptTitle: 'Thông báo'
      },
      laydate: {
        months: [
          'Tháng 1',
          'Tháng 2',
          'Tháng 3',
          'Tháng 4',
          'Tháng 5',
          'Tháng 6',
          'Tháng 7',
          'Tháng 8',
          'Tháng 9',
          'Tháng 10',
          'Tháng 11',
          'Tháng 12'
        ],
        weeks: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'],
        time: ['Giờ', 'Phút', 'Giây'],
        literal: { year: '' },
        selectDate: 'Chọn ngày',
        selectTime: 'Chọn giờ',
        startTime: 'Bắt đầu',
        endTime: 'Kết thúc',
        tools: {
          confirm: 'Xác nhận',
          clear: 'Xoá',
          now: 'Bây giờ',
          reset: 'Đặt lại'
        },
        rangeOrderPrompt: 'Ngày kết thúc không thể trước ngày bắt đầu',
        invalidDatePrompt: 'Ngoài phạm vi ngày/giờ hợp lệ',
        formatErrorPrompt:
          'Định dạng ngày không hợp lệ\nPhải theo: \n{format}\n',
        autoResetPrompt: 'Đã tự động đặt lại',
        preview: 'Kết quả đã chọn'
      },
      layer: {
        confirm: 'Xác nhận',
        cancel: 'Huỷ',
        defaultTitle: 'Thông báo',
        prompt: { InputLengthPrompt: 'Tối đa {length} ký tự' },
        photos: {
          noData: 'Không có hình ảnh',
          viewPicture: 'Xem ảnh gốc'
        }
      },
      laypage: {
        prev: 'Trang trước',
        next: 'Trang sau',
        first: 'Đầu',
        last: 'Cuối',
        total: 'Tổng {total} mục',
        pagesize: 'mục/trang',
        goto: 'Đến trang',
        page: '',
        confirm: 'OK'
      },
      table: {
        sort: { asc: 'Tăng dần', desc: 'Giảm dần' },
        noData: 'Không có dữ liệu',
        tools: {
          filter: { title: 'Lọc cột' },
          export: {
            title: 'Xuất',
            noDataPrompt: 'Bảng không có dữ liệu',
            csvText: 'Xuất CSV'
          },
          print: { title: 'In', noDataPrompt: 'Bảng không có dữ liệu' }
        },
        xhrError: 'Lỗi yêu cầu: {msg}'
      },
      dropdown: { noData: 'Không có dữ liệu' },
      upload: {
        chooseText: '{length} tệp',
        validateMessages: {
          fileOverSizeLimit: 'Kích thước tệp không được vượt quá {size}'
        }
      }
    },
    en: {
      form: {
        select: {
          noData: 'No data',
          noMatch: 'No match',
          placeholder: 'Please select'
        },
        validateMessages: {
          required: 'Required',
          phone: 'Invalid phone number',
          email: 'Invalid email',
          url: 'Invalid URL',
          number: 'Numbers only',
          date: 'Invalid date',
          identity: 'Invalid ID'
        },
        verifyErrorPromptTitle: 'Notice'
      },
      laydate: {
        months: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec'
        ],
        weeks: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
        time: ['Hour', 'Min', 'Sec'],
        literal: { year: '' },
        selectDate: 'Select date',
        selectTime: 'Select time',
        startTime: 'Start',
        endTime: 'End',
        tools: { confirm: 'OK', clear: 'Clear', now: 'Now', reset: 'Reset' },
        rangeOrderPrompt: 'End date cannot be before start date',
        invalidDatePrompt: 'Outside valid date/time range',
        formatErrorPrompt: 'Invalid date format\nMust follow:\n{format}\n',
        autoResetPrompt: 'Auto reset',
        preview: 'Selected result'
      },
      layer: {
        confirm: 'OK',
        cancel: 'Cancel',
        defaultTitle: 'Info',
        prompt: { InputLengthPrompt: 'Max {length} characters' },
        photos: {
          noData: 'No images',
          viewPicture: 'View original'
        }
      },
      laypage: {
        prev: 'Prev',
        next: 'Next',
        first: 'First',
        last: 'Last',
        total: 'Total {total}',
        pagesize: '/page',
        goto: 'Go to',
        page: '',
        confirm: 'Go'
      },
      table: {
        sort: { asc: 'Ascending', desc: 'Descending' },
        noData: 'No data',
        tools: {
          filter: { title: 'Filter columns' },
          export: {
            title: 'Export',
            noDataPrompt: 'No data to export',
            csvText: 'Export CSV'
          },
          print: { title: 'Print', noDataPrompt: 'No data to print' }
        },
        xhrError: 'Request error: {msg}'
      },
      dropdown: { noData: 'No data' },
      upload: {
        chooseText: '{length} files',
        validateMessages: {
          fileOverSizeLimit: 'File size cannot exceed {size}'
        }
      }
    }
    // zh-CN: layui đã có sẵn, không cần override
  };

  function getLang() {
    return localStorage.getItem(STORAGE_KEY) || DEFAULT_LANG;
  }

  function init() {
    var lang = getLang();

    layui.use('i18n', function () {
      var i18n = layui.i18n;

      // Thêm app messages vào mỗi locale
      Object.keys(appMessages).forEach(function (loc) {
        var merged = { app: appMessages[loc] };
        if (layuiMessages[loc]) {
          Object.keys(layuiMessages[loc]).forEach(function (k) {
            merged[k] = layuiMessages[loc][k];
          });
        }
        var msgs = {};
        msgs[loc] = merged;
        i18n.set({ messages: msgs });
      });

      // Set active locale
      i18n.set({ locale: lang });
    });
  }

  function setLang(lang) {
    if (!LANGS[lang]) return;
    localStorage.setItem(STORAGE_KEY, lang);

    layui.use('i18n', function () {
      layui.i18n.set({ locale: lang });
      applyDOM();
    });
  }

  // Đọc trực tiếp từ appMessages (sync, không cần layui.i18n)
  function t(key) {
    var lang = getLang();
    var msg = appMessages[lang] && appMessages[lang][key];
    if (msg !== undefined) return msg;
    // Fallback sang vi
    msg = appMessages.vi && appMessages.vi[key];
    return msg !== undefined ? msg : key;
  }

  function applyDOM(root) {
    root = root || document;
    var els = root.querySelectorAll('[data-i18n]');
    for (var i = 0; i < els.length; i++) {
      var el = els[i];
      var key = el.getAttribute('data-i18n');
      var text = t(key);
      if (!text || text === key) continue;

      // data-i18n-attr: thay attribute thay vì textContent
      var attr = el.getAttribute('data-i18n-attr');
      if (attr) {
        el.setAttribute(attr, text);
      } else {
        el.textContent = text;
      }
    }
  }

  return {
    LANGS: LANGS,
    getLang: getLang,
    init: init,
    setLang: setLang,
    t: t,
    applyDOM: applyDOM
  };
})();
